# Generated by Django 2.2.19 on 2022-06-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220615_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='measurement_unit',
        ),
    ]
