# Generated by Django 2.2.19 on 2022-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220618_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение рецепта', upload_to='media/', verbose_name='Изображение'),
        ),
    ]
