# Generated by Django 2.2.19 on 2022-06-16 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followauthor',
            options={'verbose_name': 'Подписчики на авторов', 'verbose_name_plural': 'Подписчики на авторов'},
        ),
        migrations.AlterField(
            model_name='followauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_users', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецептов'),
        ),
        migrations.AlterField(
            model_name='followauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_authors', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
